/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useEffect} from 'react'
import {useAnimations, useGLTF, useTexture} from '@react-three/drei'
import {GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        characterMedium: THREE.SkinnedMesh
        LeftFootCtrl: THREE.Bone
        RightFootCtrl: THREE.Bone
        HipsCtrl: THREE.Bone
    }
    materials: {
        skin: THREE.MeshStandardMaterial
    }
}

export function Model(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF('/models/characterMedium.gltf') as GLTFResult
    let texture = useTexture('models/animated-characters-2/Skins/skaterMaleA.png', (texture) => {
        if (typeof texture) {
            // console.log(typeof texture)
            // console.log('loaded')
            // console.log(texture)
        }
    })

    const {animations: idle} = useGLTF('/models/animations/idle/idle.gltf') as GLTFResult
    const {animations: run} = useGLTF('/models/animations/run/run.gltf') as GLTFResult
    const {animations: jump} = useGLTF('/models/animations/jump/jump.gltf') as GLTFResult
    // const {ref, actions} = useAnimations([...idle, ...run, ...jump])
    console.log(idle)
    console.log(run)
    console.log(jump)
    const {ref, actions} = useAnimations([idle[0], idle[1], jump[1], run[1]])


    useEffect(() => {
        console.log(actions)
        console.log(actions["Root|Run"].play())
        // actions?.jump.play()
    })

    return (
        <group {...props} dispose={null} ref={ref}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <primitive object={nodes.LeftFootCtrl}/>
                <primitive object={nodes.RightFootCtrl}/>
                <primitive object={nodes.HipsCtrl}/>
            </group>
            <skinnedMesh
                geometry={nodes.characterMedium.geometry} material={materials.skin}
                material-map={texture}
                material-map-flipY={false}
                skeleton={nodes.characterMedium.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100}/>
        </group>
    )
}

useGLTF.preload('/models/characterMedium.gltf')
