/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: leha_pu (https://sketchfab.com/leha_pu)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hot-sun-c3d84ec0290c4a04a23913edb0db3c9a
title: Hot sun
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    circle_circle_0: THREE.Mesh
    circle2_circle2_0: THREE.Mesh
    Cube088_Star_Texture_004_0: THREE.Mesh
    Plane021_Star_Texture__0: THREE.Mesh
    Cube072_Star_Texture__0: THREE.Mesh
    Cube073_Star_Texture__0: THREE.Mesh
    Cube074_Star_Texture__0: THREE.Mesh
    Cube075_Star_Texture_001_0: THREE.Mesh
    Cube077_Star_Texture__0: THREE.Mesh
    Plane022_Star_Texture__0: THREE.Mesh
    Cube078_Star_Texture__0: THREE.Mesh
    Cube079_Star_Texture__0: THREE.Mesh
    Cube080_Star_Texture__0: THREE.Mesh
    Cube081_Star_Texture__0: THREE.Mesh
    Plane025_Star_Texture__0: THREE.Mesh
    Cube082_Star_Texture__0: THREE.Mesh
    Cube083_Star_Texture__0: THREE.Mesh
    Cube084_Star_Texture__0: THREE.Mesh
    Cube085_Star_Texture__0: THREE.Mesh
  }
  materials: {
    circle: THREE.MeshBasicMaterial
    circle2: THREE.MeshBasicMaterial
    ['Star_Texture_.004']: THREE.MeshBasicMaterial
    Star_Texture: THREE.MeshBasicMaterial
    ['Star_Texture_.001']: THREE.MeshBasicMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/hot_sun/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[1.97, -0.19, 0.1]} scale={688.3}>
            <mesh castShadow receiveShadow geometry={nodes.circle_circle_0.geometry} material={materials.circle} />
          </group>
          <group position={[268.23, -176.52, -297.17]} rotation={[-1.24, 0.51, -0.17]} scale={146.85}>
            <mesh castShadow receiveShadow geometry={nodes.circle2_circle2_0.geometry} material={materials.circle2} />
          </group>
          <group position={[-188.73, -22.58, 240.37]} rotation={[-Math.PI / 2, 0, 0]} scale={58.94}>
            <mesh castShadow receiveShadow geometry={nodes.Cube088_Star_Texture_004_0.geometry} material={materials['Star_Texture_.004']} />
          </group>
          <group position={[2.25, -3.72, 134.74]} rotation={[0, 0, 0.13]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Plane021_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[265.85, -134.54, -302.02]} rotation={[1.52, -0.21, -2.91]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube072_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[268.23, -176.52, -297.17]} rotation={[-Math.PI / 2, 0.41, -0.25]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube073_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube074_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group rotation={[-Math.PI / 2, 1.53, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube075_Star_Texture_001_0.geometry} material={materials['Star_Texture_.001']} />
          </group>
          <group position={[229.69, -199.66, -303.8]} rotation={[-1.2, 1.1, -0.52]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube077_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[258.75, -172.37, -256.59]} rotation={[-0.1, -0.23, -0.42]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Plane022_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[-108.7, -59.7, 9.84]} rotation={[-Math.PI / 2, 1, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube078_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[269.12, -119.61, -302.71]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube079_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[-130.03, -70.9, 10.09]} rotation={[Math.PI / 2, -0.91, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube080_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[-267.42, -12.47, 204.09]} rotation={[-1.54, 0.23, -0.15]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube081_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[-273.62, -15.22, 286.75]} rotation={[0, -0.14, 2.17]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Plane025_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[-326.82, 38.16, 198.35]} rotation={[-2.4, -0.4, -0.84]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube082_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[-331.14, 51.08, 187.92]} rotation={[-2.13, -0.16, 2.37]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube083_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[-176.21, 1.89, 216.45]} rotation={[1.18, -0.4, -0.21]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube084_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
          <group position={[-192.07, -9.31, 223.19]} rotation={[0.96, -1, 2.78]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.Cube085_Star_Texture__0.geometry} material={materials.Star_Texture} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
