/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alexa Kruckenberg (https://sketchfab.com/AlexaKruckenberg)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/house-cat-ebcf4173da6b459f99b750a8a6972b46
title: House Cat
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    eye_R_GEO_1_house_details_0: THREE.Mesh
    eye_L_GEO_1_house_details_0: THREE.Mesh
    eye_R_GEO_2_house_details_0: THREE.Mesh
    eye_L_GEO_2_house_details_0: THREE.Mesh
    smoke_GEO_1_house_details_0: THREE.Mesh
    smoke_GEO_2_house_details_0: THREE.Mesh
    main_house_GEO_house_MAT_0: THREE.Mesh
    nose_GEO_house_details_0: THREE.Mesh
    welcome_mat_house_details_0: THREE.Mesh
    chimney_top_house_details_0: THREE.Mesh
    pCube7_house_details_0: THREE.Mesh
    pCube6_house_details_0: THREE.Mesh
    pCube8_house_details_0: THREE.Mesh
    pCube9_house_details_0: THREE.Mesh
    pCube10_house_details_0: THREE.Mesh
    pCube12_house_details_0: THREE.Mesh
    pCube11_house_details_0: THREE.Mesh
    pSphere9_house_details_0: THREE.Mesh
    pCube18_house_details_0: THREE.Mesh
    pCube17_house_details_0: THREE.Mesh
    pCube19_house_details_0: THREE.Mesh
    pCube23_house_details_0: THREE.Mesh
    pCube24_house_details_0: THREE.Mesh
    pCube25_house_details_0: THREE.Mesh
    pCube22_house_details_0: THREE.Mesh
    pCube21_house_details_0: THREE.Mesh
    pCube20_house_details_0: THREE.Mesh
    pCube16_house_details_0: THREE.Mesh
    pCube14_house_details_0: THREE.Mesh
    pCube15_house_details_0: THREE.Mesh
    pCylinder3_house_details_0: THREE.Mesh
    pCylinder2_house_details_0: THREE.Mesh
    pCylinder1_house_details_0: THREE.Mesh
    pCylinder6_house_details_0: THREE.Mesh
    pCylinder5_house_details_0: THREE.Mesh
    pCylinder4_house_details_0: THREE.Mesh
    pCylinder12_house_details_0: THREE.Mesh
    eye_L_GEO2_plant_planes_MAT_0: THREE.Mesh
    pCylinder13_house_details_0: THREE.Mesh
    eye_L_GEO3_plant_planes_MAT_0: THREE.Mesh
    pSphere1_house_details_0: THREE.Mesh
    pSphere2_house_details_0: THREE.Mesh
    pSphere8_plants_MAT_0: THREE.Mesh
    pSphere7_plants_MAT_0: THREE.Mesh
    pSphere6_plants_MAT_0: THREE.Mesh
    eye_R_GEO1_plant_planes_MAT_0: THREE.Mesh
    pSphere5_plants_MAT_0: THREE.Mesh
    pSphere4_plants_MAT_0: THREE.Mesh
    eye_R_GEO2_plant_planes_MAT_0: THREE.Mesh
    pCylinder14_house_details_0: THREE.Mesh
    pCylinder16_plants_MAT_0: THREE.Mesh
    pSphere3_plants_MAT_0: THREE.Mesh
    pCylinder15_house_details_0: THREE.Mesh
    pCylinder17_plant_planes_MAT_0: THREE.Mesh
    pCylinder11_house_details_0: THREE.Mesh
    eye_L_GEO1_plant_planes_MAT_0: THREE.Mesh
    pCylinder7_house_details_0: THREE.Mesh
    pCylinder8_house_details_0: THREE.Mesh
    pCylinder9_house_details_0: THREE.Mesh
    pCylinder10_house_details_0: THREE.Mesh
    hedge_L_plants_MAT_0: THREE.Mesh
    pCylinder18_plants_MAT_0: THREE.Mesh
    pCylinder19_plants_MAT_0: THREE.Mesh
    pCylinder20_plants_MAT_0: THREE.Mesh
    pCylinder21_plants_MAT_0: THREE.Mesh
    pCylinder22_plants_MAT_0: THREE.Mesh
    pSphere10_plants_MAT_0: THREE.Mesh
    pCylinder23_plants_MAT_0: THREE.Mesh
    pSphere11_plants_MAT_0: THREE.Mesh
    pSphere12_plants_MAT_0: THREE.Mesh
    pSphere13_plants_MAT_0: THREE.Mesh
    pSphere14_plants_MAT_0: THREE.Mesh
    pSphere15_plants_MAT_0: THREE.Mesh
    pCylinder23_plants_MAT_0_1: THREE.Mesh
    pSphere11_plants_MAT_0_1: THREE.Mesh
    pSphere13_plants_MAT_0_1: THREE.Mesh
    pSphere14_plants_MAT_0_1: THREE.Mesh
    pSphere15_plants_MAT_0_1: THREE.Mesh
    pSphere16_plants_MAT_0: THREE.Mesh
    pCylinder23_plants_MAT_0_2: THREE.Mesh
    pSphere11_plants_MAT_0_2: THREE.Mesh
    plant_plane_4_plants_MAT_0: THREE.Mesh
    plant_plane_1_plant_planes_MAT_0: THREE.Mesh
    plant_plane_2_plant_planes_MAT_0: THREE.Mesh
    plant_plane_3_plant_planes_MAT_0: THREE.Mesh
    plant_plane_5_plant_planes_MAT_0: THREE.Mesh
    plant_plane_6_plant_planes_MAT_0: THREE.Mesh
    plant_plane_7_plant_planes_MAT_0: THREE.Mesh
    plant_plane_8_plant_planes_MAT_0: THREE.Mesh
    plant_plane_10_plant_planes_MAT_0: THREE.Mesh
    plant_plane_11_plant_planes_MAT_0: THREE.Mesh
    plant_plane_13_plant_planes_MAT_0: THREE.Mesh
    plant_plane_14_plant_planes_MAT_0: THREE.Mesh
    plant_plane_15_plant_planes_MAT_0: THREE.Mesh
    plant_plane_16_plant_planes_MAT_0: THREE.Mesh
    plant_plane_17_plant_planes_MAT_0: THREE.Mesh
    plant_plane_18_plant_planes_MAT_0: THREE.Mesh
    hedge_R_plants_MAT_0: THREE.Mesh
    pCylinder23_plants_MAT_0_3: THREE.Mesh
    pSphere11_plants_MAT_0_3: THREE.Mesh
    pSphere12_plants_MAT_0_1: THREE.Mesh
    pSphere13_plants_MAT_0_2: THREE.Mesh
    pSphere14_plants_MAT_0_2: THREE.Mesh
    pSphere15_plants_MAT_0_2: THREE.Mesh
    pCylinder23_plants_MAT_0_4: THREE.Mesh
    pSphere11_plants_MAT_0_4: THREE.Mesh
    pSphere13_plants_MAT_0_3: THREE.Mesh
    pSphere14_plants_MAT_0_3: THREE.Mesh
    pSphere15_plants_MAT_0_3: THREE.Mesh
    pSphere17_plants_MAT_0: THREE.Mesh
    pSphere18_plants_MAT_0: THREE.Mesh
    pSphere1_house_details_0_1: THREE.Mesh
    pSphere2_house_details_0_1: THREE.Mesh
    pCylinder24_house_details_0: THREE.Mesh
    plant_plane_19_plant_planes_MAT_0: THREE.Mesh
    plant_plane_20_plant_planes_MAT_0: THREE.Mesh
    plant_plane_21_plant_planes_MAT_0: THREE.Mesh
    plant_plane_22_plant_planes_MAT_0: THREE.Mesh
    plant_plane_23_plant_planes_MAT_0: THREE.Mesh
    plant_plane_24_plant_planes_MAT_0: THREE.Mesh
    plant_plane_25_plant_planes_MAT_0: THREE.Mesh
    plant_plane_26_plant_planes_MAT_0: THREE.Mesh
    plant_plane_27_plant_planes_MAT_0: THREE.Mesh
    plant_plane_28_plant_planes_MAT_0: THREE.Mesh
    plant_plane_29_plant_planes_MAT_0: THREE.Mesh
    plant_plane_30_plant_planes_MAT_0: THREE.Mesh
    plant_plane_31_plant_planes_MAT_0: THREE.Mesh
    plant_plane_32_plant_planes_MAT_0: THREE.Mesh
    plant_plane_33_plant_planes_MAT_0: THREE.Mesh
    plant_plane_34_plant_planes_MAT_0: THREE.Mesh
    plant_plane_35_plant_planes_MAT_0: THREE.Mesh
    plant_plane_36_plant_planes_MAT_0: THREE.Mesh
    plant_plane_37_plant_planes_MAT_0: THREE.Mesh
    plant_plane_38_plant_planes_MAT_0: THREE.Mesh
    plant_plane_39_plant_planes_MAT_0: THREE.Mesh
    plant_plane_40_plant_planes_MAT_0: THREE.Mesh
    plant_plane_41_plant_planes_MAT_0: THREE.Mesh
  }
  materials: {
    house_details: THREE.MeshBasicMaterial
    house_MAT: THREE.MeshBasicMaterial
    plant_planes_MAT: THREE.MeshBasicMaterial
    plants_MAT: THREE.MeshBasicMaterial
  }
}

type ActionName = 'Animated'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/scene.gltf') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="092fdb6921584c448fccb2fd7b85444afbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="GEO">
                  <group name="HOUSE">
                    <group name="eye_R_GEO_1" position={[-1.65, 2.3, 0.57]}>
                      <mesh name="eye_R_GEO_1_house_details_0" castShadow receiveShadow geometry={nodes.eye_R_GEO_1_house_details_0.geometry} material={materials.house_details} />
                    </group>
                    <group name="eye_L_GEO_1" position={[1.71, 2.1, 0.57]}>
                      <mesh name="eye_L_GEO_1_house_details_0" castShadow receiveShadow geometry={nodes.eye_L_GEO_1_house_details_0.geometry} material={materials.house_details} />
                    </group>
                    <group name="eye_R_GEO_2" position={[-1.65, 2.3, 0.57]} scale={0}>
                      <mesh name="eye_R_GEO_2_house_details_0" castShadow receiveShadow geometry={nodes.eye_R_GEO_2_house_details_0.geometry} material={materials.house_details} />
                    </group>
                    <group name="eye_L_GEO_2" position={[1.71, 2.1, 0.57]} scale={0}>
                      <mesh name="eye_L_GEO_2_house_details_0" castShadow receiveShadow geometry={nodes.eye_L_GEO_2_house_details_0.geometry} material={materials.house_details} />
                    </group>
                    <group name="smoke_GEO_1" position={[2.55, 5.53, -0.11]}>
                      <mesh name="smoke_GEO_1_house_details_0" castShadow receiveShadow geometry={nodes.smoke_GEO_1_house_details_0.geometry} material={materials.house_details} />
                    </group>
                    <group name="smoke_GEO_2" position={[2.55, 5.53, -0.11]} scale={0}>
                      <mesh name="smoke_GEO_2_house_details_0" castShadow receiveShadow geometry={nodes.smoke_GEO_2_house_details_0.geometry} material={materials.house_details} />
                    </group>
                    <group name="main_house_GEO">
                      <mesh name="main_house_GEO_house_MAT_0" castShadow receiveShadow geometry={nodes.main_house_GEO_house_MAT_0.geometry} material={materials.house_MAT} />
                    </group>
                    <group name="nose_GEO">
                      <mesh name="nose_GEO_house_details_0" castShadow receiveShadow geometry={nodes.nose_GEO_house_details_0.geometry} material={materials.house_details} />
                    </group>
                    <group name="welcome_mat">
                      <mesh name="welcome_mat_house_details_0" castShadow receiveShadow geometry={nodes.welcome_mat_house_details_0.geometry} material={materials.house_details} />
                    </group>
                    <group name="chimney_top">
                      <mesh name="chimney_top_house_details_0" castShadow receiveShadow geometry={nodes.chimney_top_house_details_0.geometry} material={materials.house_details} />
                    </group>
                    <group name="door">
                      <group name="pCube7">
                        <mesh name="pCube7_house_details_0" castShadow receiveShadow geometry={nodes.pCube7_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube6">
                        <mesh name="pCube6_house_details_0" castShadow receiveShadow geometry={nodes.pCube6_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube8">
                        <mesh name="pCube8_house_details_0" castShadow receiveShadow geometry={nodes.pCube8_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube9">
                        <mesh name="pCube9_house_details_0" castShadow receiveShadow geometry={nodes.pCube9_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube10">
                        <mesh name="pCube10_house_details_0" castShadow receiveShadow geometry={nodes.pCube10_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube12">
                        <mesh name="pCube12_house_details_0" castShadow receiveShadow geometry={nodes.pCube12_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube11">
                        <mesh name="pCube11_house_details_0" castShadow receiveShadow geometry={nodes.pCube11_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pSphere9">
                        <mesh name="pSphere9_house_details_0" castShadow receiveShadow geometry={nodes.pSphere9_house_details_0.geometry} material={materials.house_details} />
                      </group>
                    </group>
                    <group name="window_L">
                      <group name="pCube18">
                        <mesh name="pCube18_house_details_0" castShadow receiveShadow geometry={nodes.pCube18_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube17">
                        <mesh name="pCube17_house_details_0" castShadow receiveShadow geometry={nodes.pCube17_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube19">
                        <mesh name="pCube19_house_details_0" castShadow receiveShadow geometry={nodes.pCube19_house_details_0.geometry} material={materials.house_details} />
                      </group>
                    </group>
                    <group name="doorway_R">
                      <group name="pCube23">
                        <mesh name="pCube23_house_details_0" castShadow receiveShadow geometry={nodes.pCube23_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube24">
                        <mesh name="pCube24_house_details_0" castShadow receiveShadow geometry={nodes.pCube24_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube25">
                        <mesh name="pCube25_house_details_0" castShadow receiveShadow geometry={nodes.pCube25_house_details_0.geometry} material={materials.house_details} />
                      </group>
                    </group>
                    <group name="doorway_L">
                      <group name="pCube22">
                        <mesh name="pCube22_house_details_0" castShadow receiveShadow geometry={nodes.pCube22_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube21">
                        <mesh name="pCube21_house_details_0" castShadow receiveShadow geometry={nodes.pCube21_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube20">
                        <mesh name="pCube20_house_details_0" castShadow receiveShadow geometry={nodes.pCube20_house_details_0.geometry} material={materials.house_details} />
                      </group>
                    </group>
                    <group name="window_R">
                      <group name="pCube16">
                        <mesh name="pCube16_house_details_0" castShadow receiveShadow geometry={nodes.pCube16_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube14">
                        <mesh name="pCube14_house_details_0" castShadow receiveShadow geometry={nodes.pCube14_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCube15">
                        <mesh name="pCube15_house_details_0" castShadow receiveShadow geometry={nodes.pCube15_house_details_0.geometry} material={materials.house_details} />
                      </group>
                    </group>
                    <group name="whiskers">
                      <group name="pCylinder3" position={[-2.93, 1.45, 0.5]}>
                        <mesh name="pCylinder3_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder3_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder2" position={[-2.61, 1.64, 0.5]}>
                        <mesh name="pCylinder2_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder2_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder1" position={[-2.24, 1.85, 0.5]}>
                        <mesh name="pCylinder1_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder1_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder6" position={[2.8, 1.84, 0.5]}>
                        <mesh name="pCylinder6_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder6_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder5" position={[2.83, 1.55, 0.5]}>
                        <mesh name="pCylinder5_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder5_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder4" position={[3, 1.28, 0.5]}>
                        <mesh name="pCylinder4_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder4_house_details_0.geometry} material={materials.house_details} />
                      </group>
                    </group>
                    <group name="window_plant_2">
                      <group name="pCylinder12">
                        <mesh name="pCylinder12_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder12_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="eye_L_GEO2">
                        <mesh name="eye_L_GEO2_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.eye_L_GEO2_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                    </group>
                    <group name="window_plant_3">
                      <group name="pCylinder13">
                        <mesh name="pCylinder13_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder13_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="eye_L_GEO3">
                        <mesh name="eye_L_GEO3_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.eye_L_GEO3_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                    </group>
                    <group name="window_cat">
                      <group name="pSphere1">
                        <mesh name="pSphere1_house_details_0" castShadow receiveShadow geometry={nodes.pSphere1_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pSphere2">
                        <mesh name="pSphere2_house_details_0" castShadow receiveShadow geometry={nodes.pSphere2_house_details_0.geometry} material={materials.house_details} />
                      </group>
                    </group>
                    <group name="tall_plant" position={[0, 0, -0.64]}>
                      <group name="pSphere8">
                        <mesh name="pSphere8_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere8_plants_MAT_0.geometry} material={materials.plants_MAT} />
                      </group>
                      <group name="pSphere7">
                        <mesh name="pSphere7_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere7_plants_MAT_0.geometry} material={materials.plants_MAT} />
                      </group>
                      <group name="pSphere6">
                        <mesh name="pSphere6_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere6_plants_MAT_0.geometry} material={materials.plants_MAT} />
                      </group>
                      <group name="eye_R_GEO1">
                        <mesh name="eye_R_GEO1_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.eye_R_GEO1_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="pSphere5">
                        <mesh name="pSphere5_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere5_plants_MAT_0.geometry} material={materials.plants_MAT} />
                      </group>
                      <group name="pSphere4">
                        <mesh name="pSphere4_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere4_plants_MAT_0.geometry} material={materials.plants_MAT} />
                      </group>
                      <group name="eye_R_GEO2">
                        <mesh name="eye_R_GEO2_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.eye_R_GEO2_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="pCylinder14">
                        <mesh name="pCylinder14_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder14_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder16">
                        <mesh name="pCylinder16_plants_MAT_0" castShadow receiveShadow geometry={nodes.pCylinder16_plants_MAT_0.geometry} material={materials.plants_MAT} />
                      </group>
                      <group name="pSphere3">
                        <mesh name="pSphere3_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere3_plants_MAT_0.geometry} material={materials.plants_MAT} />
                      </group>
                    </group>
                    <group name="small_plant">
                      <group name="pCylinder15">
                        <mesh name="pCylinder15_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder15_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder17">
                        <mesh name="pCylinder17_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.pCylinder17_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                    </group>
                    <group name="window_plant_1">
                      <group name="pCylinder11">
                        <mesh name="pCylinder11_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder11_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="eye_L_GEO1">
                        <mesh name="eye_L_GEO1_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.eye_L_GEO1_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                    </group>
                    <group name="curtains">
                      <group name="pCylinder7">
                        <mesh name="pCylinder7_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder7_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder8">
                        <mesh name="pCylinder8_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder8_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder9">
                        <mesh name="pCylinder9_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder9_house_details_0.geometry} material={materials.house_details} />
                      </group>
                      <group name="pCylinder10">
                        <mesh name="pCylinder10_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder10_house_details_0.geometry} material={materials.house_details} />
                      </group>
                    </group>
                  </group>
                  <group name="GARDEN">
                    <group name="L">
                      <group name="hedge_L">
                        <mesh name="hedge_L_plants_MAT_0" castShadow receiveShadow geometry={nodes.hedge_L_plants_MAT_0.geometry} material={materials.plants_MAT} />
                      </group>
                      <group name="tree">
                        <group name="pCylinder18">
                          <mesh name="pCylinder18_plants_MAT_0" castShadow receiveShadow geometry={nodes.pCylinder18_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pCylinder19">
                          <mesh name="pCylinder19_plants_MAT_0" castShadow receiveShadow geometry={nodes.pCylinder19_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pCylinder20">
                          <mesh name="pCylinder20_plants_MAT_0" castShadow receiveShadow geometry={nodes.pCylinder20_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pCylinder21">
                          <mesh name="pCylinder21_plants_MAT_0" castShadow receiveShadow geometry={nodes.pCylinder21_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pCylinder22">
                          <mesh name="pCylinder22_plants_MAT_0" castShadow receiveShadow geometry={nodes.pCylinder22_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere10">
                          <mesh name="pSphere10_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere10_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                      </group>
                      <group name="tall_flower_1" position={[2.37, -0.75, 1.93]} scale={0.61}>
                        <group name="pCylinder23">
                          <mesh name="pCylinder23_plants_MAT_0" castShadow receiveShadow geometry={nodes.pCylinder23_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere11">
                          <mesh name="pSphere11_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere11_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere12">
                          <mesh name="pSphere12_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere12_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere13">
                          <mesh name="pSphere13_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere13_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere14">
                          <mesh name="pSphere14_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere14_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere15">
                          <mesh name="pSphere15_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere15_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                      </group>
                      <group name="tall_flower_2" position={[3.29, 0.22, 1.53]} rotation={[0, 0, -0.18]} scale={0.7}>
                        <group name="pCylinder23_1">
                          <mesh name="pCylinder23_plants_MAT_0_1" castShadow receiveShadow geometry={nodes.pCylinder23_plants_MAT_0_1.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere11_1">
                          <mesh name="pSphere11_plants_MAT_0_1" castShadow receiveShadow geometry={nodes.pSphere11_plants_MAT_0_1.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere13_1">
                          <mesh name="pSphere13_plants_MAT_0_1" castShadow receiveShadow geometry={nodes.pSphere13_plants_MAT_0_1.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere14_1">
                          <mesh name="pSphere14_plants_MAT_0_1" castShadow receiveShadow geometry={nodes.pSphere14_plants_MAT_0_1.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere15_1">
                          <mesh name="pSphere15_plants_MAT_0_1" castShadow receiveShadow geometry={nodes.pSphere15_plants_MAT_0_1.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere16">
                          <mesh name="pSphere16_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere16_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                      </group>
                      <group name="tall_flower_3" position={[-2.06, 2.47, -1.03]}>
                        <group name="pCylinder23_2">
                          <mesh name="pCylinder23_plants_MAT_0_2" castShadow receiveShadow geometry={nodes.pCylinder23_plants_MAT_0_2.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere11_2">
                          <mesh name="pSphere11_plants_MAT_0_2" castShadow receiveShadow geometry={nodes.pSphere11_plants_MAT_0_2.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="plant_plane_4">
                          <mesh name="plant_plane_4_plants_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_4_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                      </group>
                      <group name="plant_plane_1">
                        <mesh name="plant_plane_1_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_1_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_2">
                        <mesh name="plant_plane_2_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_2_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_3">
                        <mesh name="plant_plane_3_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_3_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_5">
                        <mesh name="plant_plane_5_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_5_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_6">
                        <mesh name="plant_plane_6_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_6_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_7">
                        <mesh name="plant_plane_7_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_7_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_8">
                        <mesh name="plant_plane_8_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_8_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_10">
                        <mesh name="plant_plane_10_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_10_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_11">
                        <mesh name="plant_plane_11_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_11_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_13">
                        <mesh name="plant_plane_13_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_13_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_14">
                        <mesh name="plant_plane_14_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_14_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_15">
                        <mesh name="plant_plane_15_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_15_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_16">
                        <mesh name="plant_plane_16_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_16_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_17">
                        <mesh name="plant_plane_17_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_17_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_18">
                        <mesh name="plant_plane_18_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_18_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                    </group>
                    <group name="R">
                      <group name="hedge_R">
                        <mesh name="hedge_R_plants_MAT_0" castShadow receiveShadow geometry={nodes.hedge_R_plants_MAT_0.geometry} material={materials.plants_MAT} />
                      </group>
                      <group name="tall_flower_4" position={[-9.17, 1.39, 2.03]} rotation={[-0.05, 0.39, 0.12]} scale={[0.74, 0.74, 0.88]}>
                        <group name="pCylinder23_3">
                          <mesh name="pCylinder23_plants_MAT_0_3" castShadow receiveShadow geometry={nodes.pCylinder23_plants_MAT_0_3.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere11_3">
                          <mesh name="pSphere11_plants_MAT_0_3" castShadow receiveShadow geometry={nodes.pSphere11_plants_MAT_0_3.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere12_1">
                          <mesh name="pSphere12_plants_MAT_0_1" castShadow receiveShadow geometry={nodes.pSphere12_plants_MAT_0_1.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere13_2">
                          <mesh name="pSphere13_plants_MAT_0_2" castShadow receiveShadow geometry={nodes.pSphere13_plants_MAT_0_2.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere14_2">
                          <mesh name="pSphere14_plants_MAT_0_2" castShadow receiveShadow geometry={nodes.pSphere14_plants_MAT_0_2.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere15_2">
                          <mesh name="pSphere15_plants_MAT_0_2" castShadow receiveShadow geometry={nodes.pSphere15_plants_MAT_0_2.geometry} material={materials.plants_MAT} />
                        </group>
                      </group>
                      <group name="tall_flower_5" position={[-10.6, 1.71, -0.48]} rotation={[0.02, -0.16, 0.11]} scale={[0.82, 0.82, 0.98]}>
                        <group name="pCylinder23_4">
                          <mesh name="pCylinder23_plants_MAT_0_4" castShadow receiveShadow geometry={nodes.pCylinder23_plants_MAT_0_4.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere11_4">
                          <mesh name="pSphere11_plants_MAT_0_4" castShadow receiveShadow geometry={nodes.pSphere11_plants_MAT_0_4.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere13_3">
                          <mesh name="pSphere13_plants_MAT_0_3" castShadow receiveShadow geometry={nodes.pSphere13_plants_MAT_0_3.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere14_3">
                          <mesh name="pSphere14_plants_MAT_0_3" castShadow receiveShadow geometry={nodes.pSphere14_plants_MAT_0_3.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere15_3">
                          <mesh name="pSphere15_plants_MAT_0_3" castShadow receiveShadow geometry={nodes.pSphere15_plants_MAT_0_3.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere17">
                          <mesh name="pSphere17_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere17_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                        <group name="pSphere18">
                          <mesh name="pSphere18_plants_MAT_0" castShadow receiveShadow geometry={nodes.pSphere18_plants_MAT_0.geometry} material={materials.plants_MAT} />
                        </group>
                      </group>
                      <group name="cat" position={[0.36, -2.83, 2]} rotation={[0, 0.34, 0]}>
                        <group name="pSphere1_1">
                          <mesh name="pSphere1_house_details_0_1" castShadow receiveShadow geometry={nodes.pSphere1_house_details_0_1.geometry} material={materials.house_details} />
                        </group>
                        <group name="pSphere2_1">
                          <mesh name="pSphere2_house_details_0_1" castShadow receiveShadow geometry={nodes.pSphere2_house_details_0_1.geometry} material={materials.house_details} />
                        </group>
                        <group name="pCylinder24">
                          <mesh name="pCylinder24_house_details_0" castShadow receiveShadow geometry={nodes.pCylinder24_house_details_0.geometry} material={materials.house_details} />
                        </group>
                      </group>
                      <group name="plant_plane_19">
                        <mesh name="plant_plane_19_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_19_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_20" position={[0, -0.44, -0.74]} rotation={[-0.27, 0, 0]}>
                        <mesh name="plant_plane_20_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_20_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_21">
                        <mesh name="plant_plane_21_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_21_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_22">
                        <mesh name="plant_plane_22_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_22_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_23">
                        <mesh name="plant_plane_23_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_23_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_24">
                        <mesh name="plant_plane_24_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_24_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_25">
                        <mesh name="plant_plane_25_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_25_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_26">
                        <mesh name="plant_plane_26_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_26_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_27">
                        <mesh name="plant_plane_27_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_27_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_28">
                        <mesh name="plant_plane_28_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_28_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_29">
                        <mesh name="plant_plane_29_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_29_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_30">
                        <mesh name="plant_plane_30_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_30_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_31">
                        <mesh name="plant_plane_31_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_31_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_32">
                        <mesh name="plant_plane_32_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_32_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_33">
                        <mesh name="plant_plane_33_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_33_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_34">
                        <mesh name="plant_plane_34_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_34_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_35">
                        <mesh name="plant_plane_35_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_35_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_36">
                        <mesh name="plant_plane_36_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_36_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_37">
                        <mesh name="plant_plane_37_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_37_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_38">
                        <mesh name="plant_plane_38_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_38_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_39">
                        <mesh name="plant_plane_39_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_39_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_40">
                        <mesh name="plant_plane_40_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_40_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                      <group name="plant_plane_41">
                        <mesh name="plant_plane_41_plant_planes_MAT_0" castShadow receiveShadow geometry={nodes.plant_plane_41_plant_planes_MAT_0.geometry} material={materials.plant_planes_MAT} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
