/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react'
import {useGLTF,} from '@react-three/drei'


export default function Model(props) {
    const group = useRef()
    const {
        nodes,
        materials
    } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/bookcase-wide-broken/model.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0,]}>
                <mesh geometry={nodes.Cube034.geometry} material={materials['BrownDark.050']}/>
                <mesh geometry={nodes.Cube034_1.geometry} material={materials['PurpleDark.004']}/>
                <mesh geometry={nodes.Cube034_2.geometry} material={materials['White.035']}/>
                <mesh geometry={nodes.Cube034_3.geometry} material={materials['Metal.081']}/>
                <mesh geometry={nodes.Cube034_4.geometry} material={materials['BlueDark.004']}/>
                <mesh geometry={nodes.Cube034_5.geometry} material={materials['GreenDark.008']}/>
                <mesh geometry={nodes.Cube034_6.geometry} material={materials['WoodDark.006']}/>
                <mesh geometry={nodes.Cube034_7.geometry} material={materials['Black.031']}/>
            </group>

        </group>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/bookcase-wide-broken/model.gltf')
