/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react'
import {useGLTF,} from '@react-three/drei'


export default function Model(props) {
    const group = useRef()
    const {
        nodes,
        materials
    } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/wall/model.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0,]}>
                <mesh geometry={nodes.Cube4230.geometry} material={materials['Stone.050']}/>
                <mesh geometry={nodes.Cube4230_1.geometry} material={materials['StoneDark.011']}
                      scale={[1.01, 1, 1]} // fix z-fighting
                />
            </group>
        </group>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/wall/model.gltf')
